name: CLANG

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clang++ build
      run: clang++ -std=c++11 ./Tests/*.cpp
