name: GCC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: g++ build
      run: g++ -std=c++11 ./Tests/*.cpp
